-- AlterTable
ALTER TABLE "Aluguel" ALTER COLUMN "dataRetirada" SET DATA TYPE VARCHAR,
ALTER COLUMN "dataDevolucao" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "AutorPorLivros" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Livro" ALTER COLUMN "dataDePublicacao" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Locatario" ALTER COLUMN "dataDeNascimento" SET DATA TYPE VARCHAR;
