// src/autores/constants.ts
export const AUTOR_REPOSITORIO = 'AUTOR_REPOSITORIO';
export const LIVRO_REPOSITORIO = 'LIVRO_REPOSITORIO';
export const AUTORPORLIVRO_REPOSITORIO = 'AUTORPORLIVRO_REPOSITORIO';
export const LOCATARIO_REPOSITORIO = 'LOCATARIO_REPOSITORIO';
export const ALUGUEL_REPOSITORIO = 'ALUGUEL_REPOSITORIO';
